sudo: required
services: 
  - docker

before_install:
  - docker build -t alexanderpadin/test -f ./client/Dockerfile.dev ./client

script:
  - docker run alexanderpadin/test npm test -- --coverage

after_success:
  - docker build -t alexanderpadin/multi-client ./client 
  - docker build -t alexanderpadin/multi-nginx ./nginx 
  - docker build -t alexanderpadin/multi-server ./server 
  - docker build -t alexanderpadin/multi-worker ./worker 

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push alexanderpadin/multi-client
  - docker push alexanderpadin/multi-nginx
  - docker push alexanderpadin/multi-server
  - docker push alexanderpadin/multi-worker